See.SZA.Run is the debut mixtape by American recording artist SZA , self-released on October 29 , 2012 .
After failing college and postponing Graduation school , in order to make money , SZA began recording music by accident , and decided to continue .
SZA recorded songs with her friend who lived close by , in which they took production and beats from the internet .
A PBR&B and neo-soul , See.SZA.Run has a diverse musical style that incorporates contemporary urban genres such as soul , hip hop , and minimalist R&B , the EP also takes influences from cloud rap and ethereal R&B as well as using witch house and chillwave elements .
The production is characterized as being built over billowing synths , bombing bass and crushed beats .
Upon release the extended play was met with critical acclaim from music critics , who commended the album , its lyrical content and its production , other critics compared the album to the work of musicians including Drake , The Weeknd , Miguel and Frank Ocean .
To promote the extended play on October 9 , 2012 , SZA released a music video for the song `` Country '' .